source "http://api.berkshelf.com"

cookbook 'apache2'
cookbook 'apt'
cookbook 'aws'
cookbook 'build-essential'
cookbook 'database'
cookbook 'erlang'
cookbook 'memcached'
cookbook 'mysql'
cookbook 'openssl'
cookbook 'postgresql'
cookbook 'python'
cookbook 'rabbitmq'
cookbook 'xfs'
cookbook 'yum'
cookbook 'selinux'
cookbook 'yum-epel'
cookbook 'statsd', github: 'att-cloud/cookbook-statsd'

cookbook 'openstack-block-storage', github: 'stackforge/cookbook-openstack-block-storage'
cookbook 'openstack-common', github: 'stackforge/cookbook-openstack-common'
cookbook 'openstack-compute', github: 'stackforge/cookbook-openstack-compute'
cookbook 'openstack-dashboard', github: 'stackforge/cookbook-openstack-dashboard'
cookbook 'openstack-identity', github: 'stackforge/cookbook-openstack-identity'
cookbook 'openstack-image', github: 'stackforge/cookbook-openstack-image'
cookbook 'openstack-network', github: 'stackforge/cookbook-openstack-network'
cookbook 'openstack-object-storage', github: 'stackforge/cookbook-openstack-object-storage'
cookbook 'openstack-ops-database', github: 'stackforge/cookbook-openstack-ops-database'
cookbook 'openstack-ops-messaging', github: 'stackforge/cookbook-openstack-ops-messaging'
cookbook 'openstack-orchestration', github: 'stackforge/cookbook-openstack-orchestration'
cookbook 'openstack-telemetry', github: 'stackforge/cookbook-openstack-telemetry'

